Spandana N R AMB2261

In [ ]:
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
print(arr1)
print(arr2)
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)
print(arr1.dot(arr2))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[19 22]
 [43 50]]


In [ ]:
import numpy as np
a=np.array([0,1,2,3])
print(a)
print(type(a))
print(a.dtype)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.nbytes)

[0 1 2 3]
<class 'numpy.ndarray'>
int64
1
(4,)
4
32


In [ ]:
import numpy as np
a=np.array([[0,1,2,3],[10,11,12,13]])
print(a)
print(type(a))
print(a.dtype)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.nbytes)
print(a[1,3])
a[1,3]=-1
print(a)
print(a[0,3])
print(a[1])

[[ 0  1  2  3]
 [10 11 12 13]]
<class 'numpy.ndarray'>
int64
2
(2, 4)
8
64
13
[[ 0  1  2  3]
 [10 11 12 -1]]
3
[10 11 12 -1]


In [ ]:
import numpy as np
a=np.array([2])
print(a)
print(type(a))
print(a.dtype)
print(a.ndim)
print(a.shape)
print(a.size)


[2]
<class 'numpy.ndarray'>
int64
1
(1,)
1
2
<class 'numpy.ndarray'>
int64
0
()
1


In [ ]:
import numpy as np
a=np.array(2)
print(a)
print(type(a))
print(a.dtype)
print(a.ndim)
print(a.shape)
print(a.size)


2
<class 'numpy.ndarray'>
int64
0
()
1


In [ ]:
import numpy as np
arr=np.array([[1,2,8],[3,4,9],[5,6,7]])
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.ndim)
print(arr.shape)
print(arr.size)

[[1 2 8]
 [3 4 9]
 [5 6 7]]
<class 'numpy.ndarray'>
int64
2
(3, 3)
9


In [ ]:
import numpy as np
arr=np.array([[2.0,1],[1,2]])
print(arr)
print(arr.dtype)

[[2. 1.]
 [1. 2.]]
float64


In [ ]:
import numpy as np
arr=np.array([1,2,3,4],ndmin=5)
print(arr)
print("number of dimension:",arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimension: 5


In [ ]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr[3])

4


In [ ]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr[2]+arr[3])

7


In [ ]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("2nd element on 1st dimension:",arr[0,1])
print("5th element on 2nd dimension:",arr[1,4])

2nd element on 1st dimension: 2
5th element on 2nd dimension: 10


In [ ]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)
print()
print(arr[0,1,2])


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

6


In [ ]:
import numpy as np
arr=np.array([1,3,5,7,9])
sum=arr[0]+arr[2]
diff=arr[3]-arr[2]
product=arr[1]*arr[3]
div=arr[4]/arr[1]
print("sum of 2 numbers=",sum)
print("difference of 2 numbers=",diff)
print("product of 2 numbers=",product)
print("division of 2 numbers=",div)

sum of 2 numbers= 6
difference of 2 numbers= 2
product of 2 numbers= 21
division of 2 numbers= 3.0


In [ ]:
import numpy as np
arr=np.array([2,4,6,8,10,12,14,16,])
print(arr[3:6])
print(arr[:5])
print(arr[2:])
print(arr[-5:-1])
print(arr[:-1])
print(arr[3:-2])



[ 8 10 12]
[ 2  4  6  8 10]
[ 6  8 10 12 14 16]
[ 8 10 12 14]
[ 2  4  6  8 10 12 14]
[ 8 10 12]


In [ ]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
print(arr[1,1:4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[7 8 9]


In [ ]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
print(arr[0:2,2])
print(arr[0:2,1:4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[3 8]
[[2 3 4]
 [7 8 9]]


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5])
x=arr.copy()
arr[0]=42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(2,3,2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
np.arange(1,5)


array([1, 2, 3, 4])

In [ ]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print("originalarr.shape:",arr.shape)
print()
transposed_arr=arr.transpose()
print(transposed_arr)
print("transposed_arr.shape:",transposed_arr.shape)
print()
flattened_arr=arr.flatten()
print(flattened_arr)
print("flattened_arr.shape:",flattened_arr.shape)

[[1 2 3]
 [4 5 6]]
originalarr.shape: (2, 3)

[[1 4]
 [2 5]
 [3 6]]
transposed_arr.shape: (3, 2)

[1 2 3 4 5 6]
flattened_arr.shape: (6,)


In [ ]:
import numpy as np
a=np.array([1+1j,1+0j,4.5,3,2,2j])
print("orignal array")
print(a)
print("checking for complex number:")
print(np.iscomplex(a))
print("checking for real number:")
print(np.isreal(a))
print("checking for scalar types:")
print(np.isscalar(3.1))
print(np.isscalar([3.1]))

orignal array
[1. +1.j 1. +0.j 4.5+0.j 3. +0.j 2. +0.j 0. +2.j]
checking for complex number:
[ True False False False False  True]
checking for real number:
[False  True  True  True  True False]
checking for scalar types:
True
False


In [ ]:
import numpy as np
arr=np.zeros(5)
print(arr)

[0. 0. 0. 0. 0.]


In [ ]:
import numpy as np
arr=np.zeros((2,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
import numpy as np
one=np.ones((2,4))
print(one)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
empty=np.empty((2,3))
print(empty)

[[1. 1. 1.]
 [1. 1. 1.]]
