Spandana N R AMB2261

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
# Reading the dataset
dataset=pd.read_csv("/content/Social_Network_Ads.csv")
dataset


,User ID,Gender,Age,EstimatedSalary,Purchased
0,15624510,Male,19,19000,0
1,15810944,Male,35,20000,0
2,15668575,Female,26,43000,0
3,15603246,Female,27,57000,0
4,15804002,Male,19,76000,0
...,...,...,...,...,...
395,15691863,Female,46,41000,1
396,15706071,Male,51,23000,1
397,15654296,Female,50,20000,1
398,15755018,Male,36,33000,0


In [ ]:
# import the datasets
x=dataset.iloc[:,[2,3]].values
y=dataset.iloc[:,4].values
x
y

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,

In [ ]:
print(dataset.columns[[2,3]])
print(dataset.columns[4])

Index(['Age', 'EstimatedSalary'], dtype='object')
Purchased


In [ ]:
#splitting the dataset into train and test set
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)


In [ ]:
# feature scaling
from sklearn.preprocessing import StandardScaler
sc_x=StandardScaler()
x_train=sc_x.fit_transform(x_train)
x_test=sc_x.transform(x_test)

In [ ]:
#  create a decisiontree classifier object
from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier(criterion='entropy',max_depth=None,min_samples_split=5,min_samples_leaf=2)
model.fit(x_train,y_train)
print(model)

DecisionTreeClassifier(criterion='entropy', min_samples_leaf=2,
                       min_samples_split=5)


In [ ]:
# predict the testing model
y_pred_dec=model.predict(x_test)
y_pred_dec

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1])

In [ ]:
# making the confusion matrix
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred_dec)
cm

array([[66,  2],
       [ 6, 26]])

In [ ]:
#calculate accuracy_score
from sklearn.metrics import accuracy_score
print("Decision_tree",accuracy_score(y_test,y_pred_dec))

Decision_tree 0.92


In [ ]:
#create a object of algorithm/model
from sklearn.linear_model import LogisticRegression
modellr=LogisticRegression(random_state=0)
modellr.fit(x_train,y_train)
print(modellr)
# predict the testing model
y_pred_dec=modellr.predict(x_test)
print(y_pred_dec)
# making the confusion matrix
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred_dec)
print(cm)
#calculate accuracy_score
from sklearn.metrics import accuracy_score
print("Decision_tree",accuracy_score(y_test,y_pred_dec))

LogisticRegression(random_state=0)
[0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 1 0 0 0 0 0 0 1 0 0 0 0
 0 0 1 0 0 0 0 1 0 0 1 0 1 1 0 0 0 1 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 1 0 0 0
 0 0 1 0 1 1 1 1 0 0 1 1 0 1 0 0 0 1 0 0 0 0 0 0 1 1]
[[65  3]
 [ 8 24]]
Decision_tree 0.89


In [ ]:
# fitting the classifier into training
from sklearn.ensemble import RandomForestClassifier
RFmodel=RandomForestClassifier(n_estimators=200,criterion="entropy",random_state=0)
RFmodel.fit(x_train,y_train)
print(RFmodel)
# predict the test set results
y_pred_rf=RFmodel.predict(x_test)
print(y_pred_rf)
# making the confusion matrix
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred_dec)
print(cm)
#calculate accuracy_score
from sklearn.metrics import accuracy_score
print("Decision_tree",accuracy_score(y_test,y_pred_dec))

RandomForestClassifier(criterion='entropy', n_estimators=200, random_state=0)
[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 1 0 1 0 0 1 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0
 0 0 1 0 0 0 0 1 0 0 1 0 1 1 0 0 0 1 1 0 0 1 0 0 1 0 1 0 1 0 0 0 1 1 0 0 1
 0 0 0 0 1 1 1 1 0 0 1 0 0 1 1 0 0 1 0 0 0 0 0 1 1 1]
[[65  3]
 [ 8 24]]
Decision_tree 0.89


In [ ]:
from sklearn.naive_bayes import GaussianNB
nb = GaussianNB()
nb.fit(x_train,y_train)
y_pred_nb = nb.predict(x_test)
cmnb = confusion_matrix(y_test, y_pred_nb)
print(cmnb)
accuracy_nb = accuracy_score(y_test, y_pred_nb)
print("Accuracy:", accuracy_nb)

[[65  3]
 [ 7 25]]
Accuracy: 0.9


In [ ]:
#support vector mechine (svm) - regression,classification
from sklearn.svm import SVC
#create svm classifier object
#model=SVC
#model=svc(kernel="linear") #hyperparameter tuning
#model=SVC(kernel="poly",degree=3)
model=SVC(kernel="rbf")
#training the model
model.fit(x_train,y_train)
print(model)

SVC()


In [ ]:
# predict the testing model
y_pred_svm=model.predict(x_test)
print(y_pred_svm)
# making the confusion matrix
from sklearn.metrics import confusion_matrix
cm_SVC=confusion_matrix(y_test,y_pred_SVC)
print(cm_SVC)


[0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 1 0 0 1 0 0 1 0 1 0 1 0 0 0 0 0 0 1 0 0 0 0
 0 0 1 0 0 0 0 1 0 0 1 0 1 1 0 0 1 1 1 0 0 1 0 0 1 0 1 0 1 0 0 0 0 1 0 0 1
 0 0 0 0 1 1 1 1 0 0 1 0 0 1 1 0 0 1 0 0 0 0 0 1 1 1]
[[64  4]
 [ 3 29]]
